version: '2.2'
services:
  mysql:
    image: mysql:latest
    container_name: canal_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    networks:
      - canal_example
  redis:
    image: redis:latest
    container_name: canal_redis
    ports:
      - "6379:6379"
    networks:
      - canal_example
  canal:
    image: canal/canal-server:v1.1.5
    container_name: canal_server
    environment:
      - canal.instance.master.address=canal_mysql:3306
      - canal.instance.dbUsername=root
      - canal.instance.dbPassword=12345
      - canal.instance.connectionCharset=UTF-8
      - canal.instance.tsdb.enable=true 
      - canal.instance.gtidon=false 
    ports:
      - "11110:11110"
      - "11111:11111"
      - "11112:11112"
      - "9100:9100"
    networks:
      - canal_example

networks:
  canal_example:
    driver: bridge